import random


npc_names = {
    "Dwarf": [
        "Hera",
        "Torin",
        "Ginny",
        "Gant",
        "Olga",
        "Dendor",
        "Ygrid",
        "Pike",
        "Sarda",
        "Brigg",
        "Zorli",
        "Yorin",
        "Jorgena",
        "Trogin",
        "Riga",
        "Barton",
        "Katrina",
        "Egrim",
        "Elsa",
        "Orgo",
    ],
    "Elf": [
        "Sarenia",
        "Ravos",
        "Imeria",
        "Farond",
        "Isolden",
        "Kieren",
        "Mirenel",
        "Riarden",
        "Allindra",
        "Arlomas",
        "Sylara",
        "Tyr",
        "Rinariel",
        "Saramir",
        "Vedana",
        "Elindos",
        "Ophelia",
        "Cydaros",
        "Tiramel",
        "Varond",
    ],
    "Goblin": [
        "Kog",
        "Dibbs",
        "Fronk",
        "Irv",
        "Squag",
        "Mort",
        "Vig",
        "Sticks",
        "Gorb",
        "Yogg",
        "Plok",
        "Zrak",
        "Dent",
        "Krik",
        "Mizzo",
        "Bort",
        "Nabo",
        "Hink",
        "Bree",
        "Kreeb",
    ],
    "Halfling": [
        "Myrtle,",
        "Robby",
        "Nora",
        "Percy",
        "Daisy",
        "Jolly",
        "Evelyn",
        "Horace",
        "Willie",
        "Gertie",
        "Peri",
        "Carlsby",
        "Nyx",
        "Kellan",
        "Fern",
        "Harlow",
        "Moira",
        "Sage",
        "Reenie",
        "Wendry",
    ],
    "Half-Orc": [
        "Troga",
        "Boraal",
        "Urgana",
        "Zoraal",
        "Scalga",
        "Krell",
        "Voraga",
        "Morak",
        "Draga",
        "Sorak",
        "Varga",
        "Ulgar",
        "Jala",
        "Kresh",
        "Zana",
        "Torvash",
        "Rokara",
        "Gartak",
        "Iskana",
        "Ziraak",
    ],
    "Human": [
        "Hesta",
        "Matteo",
        "Rosalin",
        "Endric",
        "Kiara",
        "Yao",
        "Corina",
        "Rowan",
        "Hariko",
        "Ikam",
        "Mariel",
        "Jin",
        "Hana",
        "Lios",
        "Indra",
        "Remy",
        "Nura",
        "Vakesh",
        "Una",
        "Nabilo",
    ],
}


def gen_npc_name(ancestry):
    return random.choice(npc_names.get(ancestry))


def gen_npc_name_by_syllables():
    syllables = {
        "prefix": [
            "Ir",
            "Van",
            "Cyr",
            "Den",
            "Cor",
            "Hil",
            "Sal",
            "Bri",
            "Mar",
            "Gar",
            "Tin",
            "Vor",
            "Nel",
            "Ri",
            "Quor",
            "Bal",
            "Mur",
            "Par",
            "Tor",
            "Lem",
        ],
        "syllable2": [
            "an",
            "ish",
            "tos",
            "zar",
            "ven",
            "sen",
            "win",
            "on",
            "en",
            "lin",
            "sor",
            "oc",
            "vyn",
            "al",
            "osh",
            "er",
            "in",
            "el",
            "un",
            "nar",
        ],
        "syllable3": [
            "l",
            "n",
            "pil",
            "g",
            "z",
            "bor",
            "t",
            "c",
            "ar",
            "q",
            "v",
            "iv",
            "ov",
            "b",
            "den",
            "k",
            "s",
            "r",
            "jen",
            "w",
        ],
        "suffix": [
            "int",
            "us",
            "ios",
            "el",
            "inne",
            "os",
            "ian",
            "ius",
            "iol",
            "an",
            "isk",
            "erg",
            "ent",
            "ial",
            "ant",
            "iel",
            "onne",
            "org",
            "enne",
            "ynne",
        ],
    }
    prefix = random.choice(syllables.get("prefix"))
    second = random.choice(syllables.get("syllable2"))
    third = random.choice(syllables.get("syllable3"))
    suffix = random.choice(syllables.get("suffix"))

    middle = [second, third, second + third]

    return "".join([prefix, random.choice(middle), suffix])


if __name__ == "__main__":
    ancestries = ["Dwarf", "Elf", "Goblin", "Halfling", "Half-Orc", "Human"]
    for ancestry in ancestries:
        name = gen_npc_name(ancestry)
        print(f"Some {ancestry} name: {name}")

    print("Some totally random names")
    for _ in range(5):
        print(gen_npc_name_by_syllables())
